version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DBURL=postgres://postgres:postgres@db:5432/effective_mobile
      - JWT_SECRET=super_puper_sekretik

  db:
    image: postgres:13
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: effective_mobile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"